name: insta_getx
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.1
  cached_network_image: ^3.2.0
  expandable_text: ^2.2.0
  quiver: ^3.0.1+1
  photo_manager: ^1.3.10
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.8
  google_sign_in: ^5.2.4
  cloud_firestore: ^3.1.10
  image_picker: ^0.8.4+11
  firebase_storage: ^10.2.9
  photofilters: ^3.0.1
  path: ^1.8.0
  uuid: ^3.0.6
  timeago: ^3.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
